services:
  letsencrypt-proxy:
    container_name: letsencrypt-proxy
    image: nginxproxy/nginx-proxy:alpine
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - letsencrypt-vhost:/etc/nginx/vhost.d
      - letsencrypt-certs:/etc/nginx/certs:ro
      - letsencrypt-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - letsencrypt-proxy-tier
      - letsencrypt-network

  letsencrypt-companion:
    container_name: letsencrypt-companion
    image: nginxproxy/acme-companion
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: 3
    depends_on:
      - letsencrypt-proxy
    volumes:
      - letsencrypt-acme:/etc/acme.sh
      - letsencrypt-vhost:/etc/nginx/vhost.d
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - letsencrypt-proxy-tier


networks:
  letsencrypt-proxy-tier:
    name: letsencrypt-proxy-tier
    driver: bridge
  letsencrypt-network:
    name: letsencrypt-network
    driver: bridge

volumes:
  letsencrypt-acme:
    name: letsencrypt-acme
  letsencrypt-vhost:
    name: letsencrypt-vhost
  letsencrypt-certs:
    name: letsencrypt-certs
  letsencrypt-html:
    name: letsencrypt-html
